name: Playwright Tests

on:
  push:
    branches: [main, master] # Trigger tests on pushes to main or master branches
  pull_request:
    branches: [main, master] # Trigger tests on pull requests to main or master branches
  schedule:
    - cron: "0 */4 * * *" # Run smoke tests every 4 hours
  workflow_dispatch: # Allow manual trigger of the workflow
    inputs:
      testType:
        description: "Specify the type of tests to run (smoke/regression)"
        required: true
        default: "regression"
        type: string

jobs:
  test:
    timeout-minutes: 60 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium] # Specify the browser to run tests 

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "push" ]]; then
            echo "Running smoke tests..."
            npx playwright test --grep "@smoke" --project=${{ matrix.browser }}
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.testType }}" == "regression" ]]; then
            echo "Running regression tests..."
            npx playwright test --grep "@regression" --project=${{ matrix.browser }}
          else
            echo "No matching condition for tests. Skipping."
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: playwright-report
          path: playwright-report/ 
          retention-days: 30 
